### ISSUE TITLE
All-in-One - one component for getting starters

### ISSUE THREAD

**Issue by shomiron** [dnif/roadmap#2]
**Tell us about the new feature**
Scale down the footprint for smaller installations

**How will this feature connect into the product?**
The current deployment footprint is not quite optimized for smaller deployments and specially for users who would like to try the product on the laptop or a single server.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It is hard to install all the components in a single server or even a laptop, there might be clashes in running all the container images on a single docker host.

**Are you currently working around the issue?**
Yes - by throwing more hardware, not quite optimal. Sets an entry barrier for folks who would like to get started cheap, play with the software, or even researchers who don't have access to the required compute.

**Additional context**
nah - made my point

**Comment by nikhil-salgaonkar** [comment]
Architecturally not feasible for the on-premise software. 
Towards making the on-premise DNIF software more accessible for learning and experimentation, we have been able to reduce datanode CPU requirement to 8 cores.
