### ISSUE TITLE
Fallback section works with 'Other' only

### ISSUE THREAD

**Issue by BodhiSaar** [dnif/roadmap#48]
**Issue description**
The Extractor fallback section does not work with any other value except 'Other'. 

**Steps to reproduce the issue**
1.  Edit any existing yml
2.  In the Fallback section which results into Other stream, give any other name
3.  The Search block's drop down fails to display the renamed stream value

**What's the expected result?**
- Expected to see the renamed Stream into Search block's Stream dropdown 

**What's the actual result?**
- The custom stream specified in the Fallback does not show up in the drop down

**Additional details / screenshot** 
- This bug is reported by a Forum user
- https://forum.dnif.it/t/code-block-name-int-is-not-defined/158/5

See the screenprints below:
![image](https://user-images.githubusercontent.com/64898266/125439914-eb53a7dc-f8b1-4239-9fc1-4e778ba11c82.png)
![image (29)](https://user-images.githubusercontent.com/64898266/125440156-bf762947-6034-4a96-8b50-a257337f4fd8.png)

**Comment by nikhil-salgaonkar** [comment]
Fixed in 9.1.0.
