### ISSUE TITLE
HyperCloud - Test connector configuration

### ISSUE THREAD

**Issue by shomiron** [dnif/roadmap#74]
**Tell us about the new feature**
Need the ability to test configurations while setting up connectors

**How will this feature connect into the product?**
After you configure a connector you can only save, it would be great to have an intermediate step where the configured settings can be tested to see if they are successful or not. This could also be used for troubleshooting if there is a breakdown at a later date.

**Comment by nikhil-salgaonkar** [comment]
same as #87 . added to the board. planned for 920.
