### ISSUE TITLE
Enrichment | Request to add a field that mentions flagged IOCs

### ISSUE THREAD

**Issue by Blackbird2Raven** [dnif/roadmap#86]
**Tell us about the new feature**
For readily aavailable enrichments, $Intel and $IntelRef provides only mention of the enrichment vendor that is appended to the event where IOC matches. For example, in case of Greensnow - althought the enrichment is applied to both $SrcIP (Source IP), $DstIP (Destination IP) and $RemoteIP (Remote IP Address) - there is no field to highlight what IOC matched with Greensnow threat intel database. 

**How will this feature connect into the product?**
Will add a clear context to the enriched events and make it easy to triage indicators.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For readily aavailable enrichments, $Intel and $IntelRef provides only mention of the enrichment vendor that is appended to the event where IOC matches. For example, in case of Greensnow - althought the enrichment is applied to both $SrcIP (Source IP), $DstIP (Destination IP) and $RemoteIP (Remote IP Address) - there is no field to highlight what IOC matched with Greensnow threat intel database. 

**Are you currently working around the issue?**
Manually copy pasting the IP and matching with Greensnow intel database feeds available online.

**Additional context**
A different field mentioning what field value was flagged will make it really eaasy to aggregate directly from console and raise alerts.

**Comment by nikhil-salgaonkar** [comment]
DNIF is working on a native Threat Intelligence service that will enable both realtime as well as retrospective IOC matching. The new mechanism will not rely on enrichment. The output will be a signal raised with the suspect IOC appropriately highlighted.

**Comment by Blackbird2Raven** [comment]
Hi @nikhil-salgaonkar - Thanks for the response. Just curious, how will the 3rd party enrichment feeds be supported then?

**Comment by nikhil-salgaonkar** [comment]
Hi @Blackbird2Raven - no commitments on this but once the native TI service is operational, further roadmap could accomodate 3rd party or customer defined datasets. As of now, I can offer a workaround for the enrichment centric workflow:
![image](https://user-images.githubusercontent.com/2090470/144040531-e34f4498-5b03-40f6-bf6d-7a421bc2ccee.png)
Adding the highlighted config to the translate section would ensure that the IntelMatch field contains the value for the TI match.
That IntelMatch field could then be used in a subsequent signal block for suspect host mapping.
