### ISSUE TITLE
Better control and Visibility on Native WorkBooks

### ISSUE THREAD

**Issue by gauravtango** [dnif/roadmap#90]
**Tell us about the new feature**

There are following requests from SOC partner to get better synchronization on __Native Workbook updates__ -     

|Sr.No.| Request |
|:---|:---|
| 1 | Requesting a Release-note for all newly-add, Removed, updated and stream-deactivated workbooks.|
| 2 | Suggestion on UI (Console) for Workbook-Summery-widget that will display the Statistic count of total Workbook, No of Streaming Workbooks, Disabled, etc. |
| 3 | Also, the time-to-display of banner i.e. get displayed for New and Update in Workbook section is requested to get increased to get noticed if someone missed on first-time. |

**How will this feature connect into the product?**
Workbook Page with Stats and Long displayed banned or with some latest/historic release notes button. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
SOC partner wants better clarity on release/update mechanism. As for the custom changes -
1. They are already making a copy and disabling a native.
2. But they are also relying on several native WBooks too for detection.  

For Point 1, there is no issues as disabled workbook wont auto-stream till manually enabled.
Whereas for Point 2, they need more transparency on release material.  

**Are you currently working around the issue?**
Yes, by making a copy of all workbooks and disabling the native. But without updates on changes, the copied WBs become static even if better logic been released by DNIF. Without, transparent update its bit challenging to know to when to sync and update copied content.

**Additional context**
Not - Applicable

**Comment by nikhil-salgaonkar** [comment]
There is a changelog published at:
https://docs.dnif.it/docs/content-changelog
https://docs.dnif.it/docs/extractor-changelog
